- name: Deploy API en Windows
  hosts: all
  tasks:

    - name: Crear carpeta
      win_file:
        path: C:\mi_api
        state: directory

    - name: Copiar código
      win_copy:
        src: .
        dest: C:\mi_api\

    - name: Instalar dependencias
      win_shell: pip install -r C:\mi_api\requirements.txt

    - name: Ejecutar API y guardar log
      win_shell: |
        cd C:\mi_api
        python -m uvicorn main:app --host 0.0.0.0 --port 8000 > C:\mi_api\log.txt 2>&1
